### ISSUE TITLE
Handling pinned messages that aren't text

### ISSUE THREAD

**Issue by jotok** [HurrSlack/pinwheel#2]
For example, how should we handle a pinned image?

**Comment by zetlen** [comment]
two choices: either the bot makes pinned files public, via https://api.slack.com/methods/files.sharedPublicURL, or it downloads the file and uploads it to the twitter media api, https://dev.twitter.com/rest/media/uploading-media. first sure seems easier

**Comment by zetlen** [comment]
Did this in #21.
